### PR TITLE
add proper handling for DS18S20

### PR DESCRIPTION
**Pull request by susisstrolch**
DS18S20 and DS18B20 differ in precision and data format.
This pull request handles those differences. In addition, it avoids float arithmetic and introduces two macros for DS18x20 family codes.

### CODE REVIEW

**Comment by darkbyte-ru** [comment]
Thanks!

**Comment by susisstrolch** [comment]
I'm thinking about refactoring the DS18B20 code even more, so that it's 
similiar to the DHT11/22.
By using a DS18B20 init <gpio> <flag> we can in addition:
- add a dynamic array holding the addr of each detected DS18x20
- add selectiv read, like "ds18b20 3 4 7" - read out device #3, #4, #7
- add simplified read all, like "ds18b20" reading each and any device 
  (as we already do by ds18b20 <gpio> all

Using the <flag> could differentiate between human and machine readable 
format:
     human:    [ADDR] "Temperature: 99.99 °C"
     machine:    [index] "999"   (temp in 1/10 °C)
It also would allow to switch between °C and Fahrenheit...

DHT11/22 will follow later...

**Comment by darkbyte-ru** [comment]
It is need refactoring, but do not make it more complex. Currently ds18b20 module is on top2 place by flash memory consumption:

```
   text    data     bss     dec     hex filename
   2869      32       0    2901     b55 build/app/microrl.o
   2776      28      16    2820     b04 build/app/cmd_ds18b20.o
   1999       1       3    2003     7d3 build/app/i2c_master.o
   1994     112      24    2130     852 build/app/cmd_iw.o
   1745     136       0    1881     759 build/app/main.o
   1685      96       4    1785     6f9 build/app/svc_telnet.o
   1509      28      24    1561     619 build/app/cmd_dht11.o
   1475      28       4    1507     5e3 build/app/cmd_tftp.o
   1361       0       0    1361     551 build/app/tcpservice.o
   1346      28      23    1397     575 build/app/i2c_bmp180.o
   1330      64     368    1762     6e2 build/app/console.o
   1226      28       9    1263     4ef build/app/cmd_dht22.o
   1194     112       0    1306     51a build/app/cmd_flash.o
   1190       0      12    1202     4b2 build/app/env.o
   1132      28       0    1160     488 build/app/cmd_i2c.o
    981      28       0    1009     3f1 build/app/cmd_ifconfig.o
```

At the momeny, frankenstein take 44% of flash memory, but for OTA updates (via tftp) it must be less 50%. So smaller code will be better.

Selection of °C or Fahrenheit may be done by bulld config. Because usually those who use Celsius, is not using Fahrenheit, and vice versa.

**Comment by susisstrolch** [comment]
How did you create this list?

**Comment by darkbyte-ru** [comment]
```
~/src/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-size build/app/*.o
```

**Comment by susisstrolch** [comment]
But the 2766 for ds18b20 is with dbg enabled...
With -Os, I get
2166         28         16       2210        8a2 build/app/cmd_ds18b20.o

**Comment by darkbyte-ru** [comment]
Oh, yep, forgot about it. I push update just now for ds18b20, little optimization.

**Pull request merged**
